### PR TITLE
Log Encryption

### PR DESCRIPTION
**Pull request by Kevin-Woodman**
Wrote encryption / decryption for logs,
Left a copy of the data unencrypted to keep current logs in the database working and for debugging purposes, this SHOULD BE REMOVED before the end of the project. 
Encryption uses aes256 encryption. 

Only important file change is: packages/express-backend/services/user-service.js

### CODE REVIEW

**Comment by Kevin-Woodman** [comment]
Closing until other branches are merged into main

**Comment by Kevin-Woodman** [comment]
Reopening

**Comment by Kevin-Woodman** [comment]
Removed the Unecrypted logs, all logs are now always encrypted.

**Comment by amandayu255** [comment]
LGTM!

**Pull request merged**
