### PR TITLE
Analytics Component

### PR DESCRIPTION
**Pull request by King-Z-101**
Created an Analytics Component on Frontend that uses Endpoints to retrieve data of users that are logged in and display them with the chart.js library. Has been formatted already.

### CODE REVIEW

**Comment by clngo** [comment]
Glad to see the tests pass now, good work!

**Comment by Kevin-Woodman** [comment]
Looks good! Thanks for showing it off earlier today as well. It looked amazing.

**Comment by syanase-calpoly** [comment]
Nice feature

**Comment by eriksolis** [comment]
LGTM!

**Comment by amandayu255** [comment]
LGTM!

**Pull request merged**
