### PR TITLE
Backend User Creation

### PR DESCRIPTION
**Pull request by Kevin-Woodman**
Fixed some issues in backend user creation:

- The code would never say a username was already in use even if it was, this was due to it treating and array like a string
- The code would give misleading html codes (i.e 401 when it was a server error) 

Additionally fixed a bug in the calendar (front end) where it wouldn't accept dates that have a zero appended. 

I also removed some old debug code that was a security risk ( the "/users" path in backend)

### CODE REVIEW

**Comment by syanase-calpoly** [comment]
These changes seem to work and do solve the issues that are listed.

**Comment by clngo** [comment]
Great job! The implementation looks good!

**Comment by eriksolis** [comment]
LGTM!!!!

**Comment by King-Z-101** [comment]
Your changes integrated seemlessly with my branch. Good job!

**Comment by amandayu255** [comment]
LGTM!

**Pull request merged**
