### PR TITLE
Error messages

### PR DESCRIPTION
**Pull request by syanase-calpoly**
Added error messages for when login/signup errors:
- when username is already taken in signup
- when login username or password is wrong
- also quick message for when successful

Also changed one line in backend:
if(!retrievedUser) {
to
if (!retrievedUser || retrievedUser.length === 0) {
since even if the username didn't exist the previous wouldn't work

### CODE REVIEW

**Comment by Kevin-Woodman** [comment]
Looks great! Thanks for catching the error in the backend aswell.

**Comment by eriksolis** [comment]
LGTM!

**Comment by clngo** [comment]
Thanks for cleaning up the login and signup!

**Comment by amandayu255** [comment]
LGTM!

**Comment by King-Z-101** [comment]
It seems your branch has merge conflicts with main that you should fix. Make sure to run npm format if you haven't already.

**Pull request merged**
