### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by clngo**
Added PropTypes to ensure proper type validation for components.     
Resolved various linting errors to improve code quality and maintain consistency with project standards.  

These changes help enhance the maintainability and readability of the codebase.

### CODE REVIEW

**Comment by Kevin-Woodman** [comment]
Thank you for doing this! We should re-enable linting as a test in the CI now that the front end passes. If you want I can do that and push to this branch?

**Comment by eriksolis** [comment]
LGTM!

**Comment by King-Z-101** [comment]
Have you run npm run format already?

**Comment by syanase-calpoly** [comment]
Nice changes

**Comment by amandayu255** [comment]
LGTM!

**Pull request merged**
